name: Feature Request
description: Suggest an idea for this project
labels: [Enhancement]
body:
- type: textarea
  attributes:
    description: Please describe the desired feature/behaviour. Supporting images/mockups, or example reference videos are very helpful to communicate ideas.
  validations:
    required: true
